language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - sh run_travis.sh
  - nosetests --exe --with-coverage --cover-package=runtest
  - coveralls
after_success:
  - coveralls